
module.exports = {
    ID_TIPO_MOVIMIENTO_VENTA :1,
    ID_TIPO_MOVIMIENTO_COMPRAS:2,
    ID_TIPO_MOVIMIENTO_AJUSTE_ENTRADA:3,
    ID_TIPO_MOVIMIENTO_AJUSTE_SALIDA:4,
    ID_TIPO_MOVIMIENTO_AJUSTE_LIBRE:5,
    ID_TIPO_DEVOLUCION_VENTA:6,
    ID_TIPO_CANCELACION_VENTA:7,
};